Added capture video functionality
zhihu/Matisse pull request #90
Opened 2017-06-05 13:07 UTC by kaadzr

I can't capture any video (Camera app crashes), but in theory it must works

2017-06-06 07:00 UTC, gejiaheng requested changes
Thanks for this PR. It's very useful.

2017-06-06 07:00 UTC, gejiaheng commented on matisse/src/main/java/com/zhihu/matisse/internal/model/AlbumMediaCollection.java
> +                (AlbumMediaLoader.Capture) args.getSerializable(ARGS_CAPTURE));
I notice that you removed `album.isAll()` condition. This will make capture entries appear on every album page.

2017-06-06 07:00 UTC, gejiaheng commented on matisse/src/main/java/com/zhihu/matisse/internal/ui/adapter/AlbumMediaAdapter.java
> +        }
The above is redundant.

2017-06-06 07:00 UTC, gejiaheng commented on matisse/src/main/java/com/zhihu/matisse/internal/utils/MediaStoreCompat.java
> +        }
The private and public directory should be `Environment.DIRECTORY_DCIM` or `Environment.DIRECTORY_MOVIES`? Actually I'm not sure about this. But they should be the same.

2017-06-06 07:00 UTC, gejiaheng commented on matisse/src/main/java/com/zhihu/matisse/ui/MatisseActivity.java
> +        } else if (requestCode == REQUEST_CODE_CAPTURE_PHOTO) {
Here should be `if (requestCode == REQUEST_CODE_CAPTURE_PHOTO || requestCode == REQUEST_CODE_CAPTURE_VIDEO)`

2017-06-07 13:58 UTC, unixzii requested changes

2017-06-07 13:58 UTC, unixzii commented on matisse/src/main/java/com/zhihu/matisse/internal/loader/AlbumMediaLoader.java
> +        return new String[]{
Missed a whitespace here.

2017-06-08 08:42 UTC, kaadzr commented on matisse/src/main/java/com/zhihu/matisse/internal/model/AlbumMediaCollection.java
> +                (AlbumMediaLoader.Capture) args.getSerializable(ARGS_CAPTURE));
`album.isAll()` condition is also checked in `AlbumMediaLoader.newInstance()` method. In my opinion, this check is not needed here. However, in practice, the capture buttons will only appear in the category "All media".

2017-06-08 09:12 UTC, kaadzr commented on matisse/src/main/java/com/zhihu/matisse/internal/utils/MediaStoreCompat.java
> +        }
On my MIUI8.3 and on my cyanogen11 camera app saves the files in DCIM. I think all media from the camera shold be saved in `Environment.DIRECTORY_DCIM`

2017-06-10 02:37 UTC, gejiaheng commented on matisse/src/main/java/com/zhihu/matisse/internal/model/AlbumMediaCollection.java
> +                (AlbumMediaLoader.Capture) args.getSerializable(ARGS_CAPTURE));
Got it.

2017-06-10 02:40 UTC, gejiaheng commented on matisse/src/main/java/com/zhihu/matisse/internal/utils/MediaStoreCompat.java
> +        }
Then I think you should change both to `Environment.DIRECTORY_DCIM`

2017-06-10 02:42 UTC, gejiaheng commented
@kaadzr 
In case you are not sure about it. You can go on pushing new commits to the source branch which is `kaadzr:master`. And also don't forget to rebase against zhihu:master as I have merged some other PRs.

2017-06-16 09:58 UTC, gejiaheng commented
Any reason you closed this PR? Really awesome feature.

2017-06-22 06:04 UTC, gejiaheng requested changes

2017-06-22 06:04 UTC, gejiaheng commented on matisse/src/main/res/values-it/strings.xml
> -</resources>
You have accidentally removed a commit from another contributor.

2017-06-22 08:37 UTC, kaadzr commented on matisse/src/main/res/values-it/strings.xml
> -</resources>
Hell! I can not even guess how it happened=(

2017-09-21 13:48 UTC, gejiaheng commented
@kaadzr Sorry, I can't merge this PR right now due to the following two reasons:
- CI failed because of code style
- The commit history is somewhat in a mess

2018-02-27 16:14 UTC, youssefwagih commented
any updates on this issue plz as i need it in my project. thanks for your great efforts.

2018-10-10 13:26 UTC, closed without merging

2021-06-14 09:56 UTC, Miteshmakwana73 commented
@gejiaheng is video capture feature is available?